CREATE DATABASE IF NOT EXISTS curso_angular4;

USE curso_angular4;

CREATE TABLE PRODUCTOS (
    ID INT(255) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(255),
    DESCRIPCION TEXT,
    PRECIO VARCHAR(255),
    IMAGEN VARCHAR(255),
    CONSTRAINT PRODUCTOS_PK PRIMARY KEY(ID)
) ENGINE=InnoDb;





