CREATE DATABASE IF NOT EXISTS curso_angular4;

USE curso_angular4;

CREATE TABLE PRODUCTOS (
    id INT(255) AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(255),
    descripcion TEXT,
    precio VARCHAR(255),
    imagen VARCHAR(255),
    CONSTRAINT PRODUCTOS_PK PRIMARY KEY(id)
) ENGINE=InnoDb;





